export const GET_ASSETS_START = "GET_ASSETS_START"
export const GET_ASSETS_SUCCESS = "GET_ASSETS_SUCCESS"
export const GET_ASSETS_FAIL = "GET_ASSETS_FAIL"

export const GET_CURRENT_LIMIT = "GET_CURRENT_LIMIT"

export const GET_ASSET_HISTORY_START = "GET_ASSET_HISTORY_START"
export const GET_ASSET_HISTORY_SUCCESS = "GET_ASSET_HISTORY_SUCCESS"
export const GET_ASSET_HISTORY_FAIL = "GET_ASSET_HISTORY_FAIL"